export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_SELECTED_STATION = 'SET_SELECTED_STATION';
export const CLEAR_SELECTED_STATION = 'CLEAR_SELECTED_STATION';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
